export default {
  elements: [
    {
      key: 'Room',
      url: require('assets/room.jpg'),
      x: 0,
      y: 0,
    }, {
      key: 'DecorTable',
      url: require('assets/decor_table.png'),
      x: 230,
      y: 210,
    }, {
      key: 'DecorPaint1',
      url: require('assets/decor_paint1.png'),
      x: 450,
      y: -35,
    }, {
      key: 'DecorPaint12',
      texture: 'DecorPaint1',
      x: 1135,
      y: 170,
    }, {
      key: 'DecorGlobe',
      url: require('assets/decor_globe.png'),
      x: 110,
      y: 130,
    }, {
      key: 'DecorBookStand',
      url: require('assets/decor_book_stand.png'),
      x: 840,
      y: -30,
    }, {
      key: 'DecorSofa',
      url: require('assets/decor_sofa.png'),
      x: 150,
      y: 330,
    }, {
      key: 'Austin',
      url: require('assets/Austin.png'),
      x: 700,
      y: 110,
    }, {
      key: 'StairOld',
      url: require('assets/stair_old.png'),
      x: 900,
      y: 0,
    }, {
      key: 'StairNew1',
      url: require('assets/stair_new_01.png'),
      x: 900,
      y: 0,
      visible: false,
    }, {
      key: 'StairNew2',
      url: require('assets/stair_new_02.png'),
      x: 900,
      y: 0,
      visible: false,
    }, {
      key: 'StairNew3',
      url: require('assets/stair_new_03.png'),
      x: 900,
      y: 0,
      visible: false,
    }, {
      key: 'DecorPaint2',
      url: require('assets/decor_paint2.png'),
      x: 1150,
      y: 430,
    }, {
      key: 'MenuCircle',
      url: require('assets/menu_circle.png'),
      disabled: true,
    }, {
      key: 'MenuCircleChoosed',
      url: require('assets/menu_circle_choosed.png'),
      disabled: true,
    }, {
      key: 'MenuBtn1',
      texture: 'MenuCircle',
      x: 0,
      y: 0,
      container: 'menu',
    }, {
      key: 'MenuBtn2',
      texture: 'MenuCircle',
      x: 130,
      y: 0,
      container: 'menu',
    }, {
      key: 'MenuBtn3',
      texture: 'MenuCircle',
      x: 260,
      y: 0,
      container: 'menu',
    }, {
      key: 'SmallStairNew1',
      url: require('assets/small_stair_new_01.png'),
      x: 0,
      y: 0,
      anchor: 0.5,
      container: 'menu',
    }, {
      key: 'SmallStairNew2',
      url: require('assets/small_stair_new_02.png'),
      x: 0,
      y: 0,
      anchor: 0.5,
      container: 'menu',
    }, {
      key: 'SmallStairNew3',
      url: require('assets/small_stair_new_03.png'),
      x: 0,
      y: 0,
      anchor: 0.5,
      container: 'menu',
    }, {
      key: 'BtnOK',
      url: require('assets/btn_ico.png'),
      x: 0,
      y: 0,
      anchor: 0.5,
      visible: false,
      container: 'menu',
    }, {
      key: 'IcoHammer',
      url: require('assets/icon_hammer.png'),
      x: 1090,
      y: 245,
      visible: false,
      alpha: 0,
    }, {
      shadow: true,
      fill: 0x000000,
      alpha: 0.75,
    }, {
      key: 'Final',
      url: require('assets/final.png'),
      x: 400,
      y: 70,
      visible: false,
    }, {
      key: 'Logo',
      url: require('assets/logo.png'),
      x: 23,
      y: 0,
    }, {
      key: 'CtaBtn',
      url: require('assets/cta_btn.png'),
      x: 702,
      y: 562,
      anchor: 0.5,
      container: 'UI',
    },
  ],

  location: 'https://playrix.com',
}
